### ISSUE TITLE
[Suggestion] 'Complete' command to announce completion of task

### ISSUE THREAD

**Issue by philnewberryls** [stwupton/project-announcer-bot#5]
Joseph mentioned it - seems like a nice idea. Could be quite satisfying for the user.

**Comment by stwupton** [comment]
If we're gonna do this, probably best to revisit how we handle projects on the due date. Currently, they are deleted when it hits the due date. But we could send something like "@user, project x is overdue by y days." until they run `pab complete [index]`.
